services:

  fixops:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: fixops

    restart: unless-stopped

    depends_on:
      - redis

    env_file:
        - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      # FixOps наблюдает Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Проекты
      - /home/virtu/projects:/projects


  frontend:
    image: nginx:alpine

    container_name: fixops-frontend

    restart: unless-stopped

    depends_on:
      - fixops

    ports:
      - "3000:80"

    volumes:
      - ./frontend:/usr/share/nginx/html:ro


  redis:
    image: redis/redis-stack:latest

    container_name: redis

    restart: unless-stopped

    command:
      - redis-server
      - --protected-mode
      - "no"
      - --requirepass
      - ${REDIS_PASSWORD}

    expose:
      - "6379"

    volumes:
      - redis-data:/data


volumes:
  redis-data:
